train:
  log-level: "debug"
  seed: 42
  N: 4096
  loss: "mse" # FIXME add implementation to code
  device: "cpu"
  epochs: 200
  batch_size: 128
  lr: 0.01
  dataset: "toy-relu"
  ratio: 0.8
  shuffle: True
  regularization:
    method: "lp"
    p: 2
  dtype: "torch.float32"
  epochs_block: 1

init:
  method: "uniform"
  uniform:
    low: 0.01
    high: 0.05
  normal:
    mean: 0.0
    std: 0.1

container:
  latent-dim: 6


projection:
  learnable: False
  activation: "identity"

output:
  activation: "identity"
  learnable: False

ode:
  solver:
    t-span: [ 0,1 ]
    method: "euler"
    euler:
      step-size: 0.1
    rk45:
      rtol: 0.001
  #--
  model: "nn"
  tt:
    activation: "identity"
    rank: "3" # string , if numeric then fixed else the string = "adaptive"
    basis:
      model: "poly"
      poly:
        deg: 4
      rbf:
        window: 1.0
  nn:
    hidden-dim: 50
